-- MySQL Script generated by MySQL Workbench
-- jeu. 15 sept. 2022 09:06:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OnlineCourses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OnlineCourses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnlineCourses` DEFAULT CHARACTER SET utf8 ;
USE `OnlineCourses` ;

-- -----------------------------------------------------
-- Table `OnlineCourses`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineCourses`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45),
  `prenom` VARCHAR(45),
  `email` VARCHAR(45),
  `password` VARCHAR(255),
  `avatar` LONGTEXT,
  `isAdmin` INT,
  `isVisiteur` INT,
  `isVerified` INT,
  `mobile` VARCHAR(45),
  `adresse` VARCHAR(255),
  `ville` VARCHAR(255),
  `codePostal` VARCHAR(5),
  `pays` VARCHAR(255),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineCourses`.`cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineCourses`.`cours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` LONGTEXT,
  `description` LONGTEXT,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `id_user` INT NOT NULL,
  `contenu` LONGTEXT,
  `image` VARCHAR(45),
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `OnlineCourses`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineCourses`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineCourses`.`categorie` (
  `id_categorie` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_article` INT NOT NULL,
  PRIMARY KEY (`id_categorie`),
  INDEX `fk_article_idx` (`id_article` ASC) VISIBLE,
  UNIQUE INDEX `id_categorie_UNIQUE` (`id_categorie` ASC) VISIBLE,
  CONSTRAINT `fk_article`
    FOREIGN KEY (`id_article`)
    REFERENCES `OnlineCourses`.`cours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineCourses`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineCourses`.`image` (
  `id_cours` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(45),
  `name` VARCHAR(45),
  UNIQUE INDEX `id_cours_UNIQUE` (`id_cours` ASC),
  CONSTRAINT `fk_cours`
    FOREIGN KEY (`id_cours`)
    REFERENCES `OnlineCourses`.`cours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineCourses`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineCourses`.`message` (
  `id_message` INT NOT NULL AUTO_INCREMENT,
  `message` LONGTEXT,
  `sujet` VARCHAR(100) ,
  `id_user` INT NOT NULL,
  UNIQUE INDEX `id_message_UNIQUE` (`id_message` ASC) VISIBLE,
  PRIMARY KEY (`id_message`),
  INDEX `fk_user_mail_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_mail`
    FOREIGN KEY (`id_user`)
    REFERENCES `OnlineCourses`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
